# Generated by Django 4.0.6 on 2022-07-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='options_or_mods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrees',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrees',
            name='options_or_mods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
