# Generated by Django 4.0.6 on 2022-07-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_apps_description_apps_options_or_mods_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='App',
        ),
        migrations.RenameModel(
            old_name='Entrees',
            new_name='Entree',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Sides',
            new_name='Side',
        ),
    ]
