# Generated by Django 4.0.6 on 2022-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_apps_app_rename_entrees_entree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entree',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='entree',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.ingredient'),
        ),
    ]
