# Generated by Django 4.0.6 on 2022-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_entree_ingredients_entree_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='sides',
            field=models.ManyToManyField(blank=True, to='frontend.side'),
        ),
        migrations.AlterField(
            model_name='entree',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='frontend.ingredient'),
        ),
    ]
