# Generated by Django 4.0.6 on 2022-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_dressing_soup_sandwich_salad_burger'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='frontend.ingredient'),
        ),
    ]
