# Generated by Django 4.0.6 on 2022-07-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_cheese_sandwich_cheese'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='cheese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.cheese'),
        ),
    ]
