# Generated by Django 4.0.6 on 2022-07-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_burger_cheese'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='options_or_mods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salad',
            name='options_or_mods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='options_or_mods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
