# Generated by Django 4.0.6 on 2022-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_burger_options_or_mods_salad_options_or_mods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
