# Generated by Django 4.0.6 on 2022-07-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('mixed', 'Mixed'), ('frozen', 'Frozen')], max_length=100)),
                ('description', models.TextField()),
                ('options_or_mods', models.TextField(blank=True, null=True)),
                ('bar_ingredients', models.ManyToManyField(blank=True, to='frontend.baringredient')),
            ],
        ),
    ]
