# Generated by Django 4.0.6 on 2022-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_baringredient_cocktail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('lager', 'Lager'), ('ipa', 'IPA')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('vodka', 'Vodka'), ('rum', 'Rum'), ('tequila', 'Tequila'), ('bourbon', 'Bourbon'), ('whiskey', 'Whiskey'), ('scotch', 'Scotch'), ('cordials', 'Cordials')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('splits', 'Splits'), ('champagne', 'Champagne')], max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
