# Generated by Django 4.0.6 on 2022-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_beer_liquor_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='d_or_b',
            field=models.CharField(choices=[('draft', 'Draft'), ('bottle', 'Bottle')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
