# Generated by Django 4.0.6 on 2022-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_beer_d_or_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='d_or_b',
        ),
        migrations.AddField(
            model_name='beer',
            name='bottle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beer',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
