# Generated by Django 4.0.6 on 2022-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_remove_beer_d_or_b_beer_bottle_beer_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('quiz_number', models.CharField(max_length=100)),
                ('question_item', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=3)),
                ('incorrect', models.CharField(max_length=3)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
    ]
