# Generated by Django 4.0.6 on 2022-07-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_quizresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizResults',
            new_name='QuizResult',
        ),
    ]
