# Generated by Django 4.0.6 on 2022-07-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_rename_quizresults_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='question_item',
        ),
    ]
