# Generated by Django 4.0.6 on 2022-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_remove_quizresult_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('quiz_number', models.CharField(max_length=100)),
                ('answer_correct', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='quizresult',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
